import React, { useState, useRef } from "react";
import { motion, AnimatePresence } from "motion/react";
import {
  Upload,
  FileSpreadsheet,
  Download,
  AlertTriangle,
  CheckCircle2,
  X,
  RefreshCw,
  Users,
  Key,
  ShieldCheck,
  Search,
  Check,
  HelpCircle,
  FileText,
  Trash2,
} from "lucide-react";
import * as XLSX from "xlsx";
import {
  DiscordUserSession,
  ALLOWED_DISCORD_ROLES,
  EmployeeTokenImportItem,
  isOwnerKey,
} from "../types";

interface TokenExcelImportModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSuccess: (count: number, mode: "overwrite" | "merge") => void;
  activeToken: string;
  isMasterSession: boolean;
  isProprietarioUser: boolean;
  existingTokens: DiscordUserSession[];
}

interface ParsedTokenPreview extends EmployeeTokenImportItem {
  isNew: boolean;
  isTokenAutoGenerated: boolean;
  originalIndex: number;
  roleRecognized: boolean;
}

export const TokenExcelImportModal: React.FC<TokenExcelImportModalProps> = ({
  isOpen,
  onClose,
  onSuccess,
  activeToken,
  isMasterSession,
  isProprietarioUser,
  existingTokens,
}) => {
  const [file, setFile] = useState<File | null>(null);
  const [fileName, setFileName] = useState<string>("");
  const [fileSize, setFileSize] = useState<string>("");
  const [isParsing, setIsParsing] = useState<boolean>(false);
  const [parsedRows, setParsedRows] = useState<ParsedTokenPreview[]>([]);
  const [parseError, setParseError] = useState<string | null>(null);

  // Import mode
  const [importMode, setImportMode] = useState<"overwrite" | "merge">("overwrite");
  const [searchTerm, setSearchTerm] = useState<string>("");

  // Submitting
  const [isSubmitting, setIsSubmitting] = useState<boolean>(false);
  const [submitError, setSubmitError] = useState<string | null>(null);
  const [submitSuccess, setSubmitSuccess] = useState<string | null>(null);

  const fileInputRef = useRef<HTMLInputElement>(null);
  const [isDragging, setIsDragging] = useState<boolean>(false);

  if (!isOpen) return null;

  // Generate and download a ready-to-use template
  const handleDownloadTemplate = (format: "xlsx" | "csv") => {
    const templateData = [
      {
        "Nome e Cognome": "Mario Rossi",
        "Grado / Ruolo EMS": "Direttore Generale",
        "Ruolo CDA": "Presidente CDA",
        "Tag Discord": "@mariorossi",
        "Token di Accesso": "EMS-MR2026",
      },
      {
        "Nome e Cognome": "Luca Bianchi",
        "Grado / Ruolo EMS": "Primario di Reparto",
        "Ruolo CDA": "Membro CDA",
        "Tag Discord": "@lucabianchi",
        "Token di Accesso": "EMS-LB7744",
      },
      {
        "Nome e Cognome": "Giulia Verdi",
        "Grado / Ruolo EMS": "Medico",
        "Ruolo CDA": "",
        "Tag Discord": "@giuliaverdi",
        "Token di Accesso": "EMS-GV9911",
      },
      {
        "Nome e Cognome": "Alessandro Neri",
        "Grado / Ruolo EMS": "Volontario",
        "Ruolo CDA": "",
        "Tag Discord": "@alessandroneri",
        "Token di Accesso": "", // Empty on purpose to test auto-generation
      },
    ];

    const worksheet = XLSX.utils.json_to_sheet(templateData);

    // Set column widths
    worksheet["!cols"] = [
      { wch: 24 }, // Nome e Cognome
      { wch: 28 }, // Ruolo EMS
      { wch: 22 }, // Ruolo CDA
      { wch: 20 }, // Tag Discord
      { wch: 20 }, // Token di Accesso
    ];

    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, "Token EMS");

    if (format === "xlsx") {
      XLSX.writeFile(workbook, "Modello_Importazione_Token_EMS.xlsx");
    } else {
      XLSX.writeFile(workbook, "Modello_Importazione_Token_EMS.csv", { bookType: "csv" });
    }
  };

  // Helper to normalize column names from Excel headers
  const matchColumnType = (header: string): "name" | "role" | "cda" | "discord" | "token" | "hide" | "dev" | null => {
    const h = header.trim().toLowerCase().replace(/[^a-z0-9]/g, "");
    if (h.includes("nome") || h.includes("dipendente") || h.includes("utente") || h.includes("nominativo") || h.includes("username")) {
      return "name";
    }
    if (h.includes("ruolocda") || h.includes("caricacda") || h.includes("badgecda") || h.includes("cda")) {
      return "cda";
    }
    if (h.includes("grado") || h.includes("ruolo") || h.includes("qualifica") || h.includes("mansione")) {
      return "role";
    }
    if (h.includes("discord") || h.includes("tag")) {
      return "discord";
    }
    if (h.includes("token") || h.includes("codice") || h.includes("chiave")) {
      return "token";
    }
    if (h.includes("gerarchia") || h.includes("nascosto") || h.includes("visibile") || h.includes("hide")) {
      return "hide";
    }
    if (h.includes("dev") || h.includes("sviluppatore")) {
      return "dev";
    }
    return null;
  };

  // Parse uploaded file
  const handleFileProcess = async (selectedFile: File) => {
    setFile(selectedFile);
    setFileName(selectedFile.name);
    setFileSize((selectedFile.size / 1024).toFixed(1) + " KB");
    setIsParsing(true);
    setParseError(null);
    setSubmitError(null);
    setSubmitSuccess(null);

    try {
      const buffer = await selectedFile.arrayBuffer();
      const workbook = XLSX.read(buffer, { type: "array" });

      if (!workbook.SheetNames || workbook.SheetNames.length === 0) {
        throw new Error("Il foglio Excel selezionato è vuoto o non leggibile.");
      }

      const firstSheetName = workbook.SheetNames[0];
      const worksheet = workbook.Sheets[firstSheetName];

      // Convert sheet to 2D array
      const rawData: any[][] = XLSX.utils.sheet_to_json(worksheet, { header: 1, defval: "" });

      if (!rawData || rawData.length === 0) {
        throw new Error("Nessuna riga trovata all'interno del foglio Excel.");
      }

      // Find header row (row that contains at least "nome" or "token" or "ruolo")
      let headerRowIndex = -1;
      let colMap: Record<string, number> = {};

      for (let r = 0; r < Math.min(rawData.length, 10); r++) {
        const row = rawData[r];
        if (!Array.isArray(row)) continue;

        let hasNameOrToken = false;
        const currentMap: Record<string, number> = {};

        row.forEach((cellVal, cIdx) => {
          const type = matchColumnType(String(cellVal || ""));
          if (type) {
            currentMap[type] = cIdx;
            if (type === "name" || type === "token") hasNameOrToken = true;
          }
        });

        if (hasNameOrToken) {
          headerRowIndex = r;
          colMap = currentMap;
          break;
        }
      }

      if (headerRowIndex === -1 || colMap["name"] === undefined) {
        // Fallback: assume column 0 is Name, column 1 is Role, column 2 is CDA, column 3 is Discord, column 4 is Token
        colMap = {
          name: 0,
          role: 1,
          cda: 2,
          discord: 3,
          token: 4,
        };
        headerRowIndex = 0;
      }

      const existingUpperTokens = new Set(
        existingTokens.map((t) => (t.token || "").trim().toUpperCase())
      );
      const existingUsernames = new Map(
        existingTokens.map((t) => [
          (t.username || "").trim().toLowerCase(),
          (t.token || "").trim().toUpperCase(),
        ])
      );

      const parsed: ParsedTokenPreview[] = [];
      const generatedTokensInBatch = new Set<string>();

      for (let r = headerRowIndex + 1; r < rawData.length; r++) {
        const row = rawData[r];
        if (!Array.isArray(row) || row.length === 0) continue;

        const rawName = String(row[colMap["name"]] || "").trim();
        if (!rawName) continue; // Skip empty rows

        const rawRole = colMap["role"] !== undefined ? String(row[colMap["role"]] || "").trim() : "Volontario";
        const rawCda = colMap["cda"] !== undefined ? String(row[colMap["cda"]] || "").trim() : "";
        const rawDiscord = colMap["discord"] !== undefined ? String(row[colMap["discord"]] || "").trim() : "";
        let rawToken = colMap["token"] !== undefined ? String(row[colMap["token"]] || "").trim().toUpperCase() : "";

        // Check if role is recognized
        const matchedRole = ALLOWED_DISCORD_ROLES.find(
          (role) => role.toLowerCase() === rawRole.toLowerCase()
        );
        const resolvedRole = matchedRole || rawRole || "Volontario";

        // Auto-generate token if empty
        let isAutoGenerated = false;
        if (!rawToken || rawToken === "-" || rawToken === "AUTO") {
          isAutoGenerated = true;
          // Generate unique token
          const initials = rawName
            .split(" ")
            .map((n) => n[0])
            .join("")
            .toUpperCase()
            .replace(/[^A-Z]/g, "")
            .slice(0, 3) || "EMP";
          let cand = `EMS-${initials}${Math.random().toString(36).substring(2, 6).toUpperCase()}`;
          while (existingUpperTokens.has(cand) || generatedTokensInBatch.has(cand)) {
            cand = `EMS-${initials}${Math.random().toString(36).substring(2, 6).toUpperCase()}`;
          }
          rawToken = cand;
          generatedTokensInBatch.add(cand);
        }

        // Discord Tag formatting
        let cleanDiscord = rawDiscord;
        if (cleanDiscord && cleanDiscord !== "-" && !cleanDiscord.startsWith("@")) {
          cleanDiscord = `@${cleanDiscord}`;
        }

        // CDA Role cleaning
        let cleanCda = rawCda;
        let hasCda = false;
        if (cleanCda && cleanCda.toLowerCase() !== "nessuno" && cleanCda.toLowerCase() !== "default" && cleanCda !== "-") {
          hasCda = true;
        } else {
          cleanCda = "";
        }

        const isTokenInExisting = existingUpperTokens.has(rawToken);
        const isNameInExisting = existingUsernames.has(rawName.toLowerCase());
        const isNew = !isTokenInExisting && !isNameInExisting;

        parsed.push({
          username: rawName,
          roleName: resolvedRole,
          cdaRoleName: cleanCda || undefined,
          hasCdaAccess: hasCda,
          discordTag: cleanDiscord || undefined,
          token: rawToken,
          isNew,
          isTokenAutoGenerated: isAutoGenerated,
          originalIndex: r + 1,
          roleRecognized: Boolean(matchedRole),
        });
      }

      if (parsed.length === 0) {
        throw new Error("Nessuna riga valida con nome dipendente trovata nel file.");
      }

      setParsedRows(parsed);
    } catch (err: any) {
      console.error("Error reading excel file:", err);
      setParseError(err.message || "Impossibile elaborare il foglio Excel selezionato.");
      setParsedRows([]);
    } finally {
      setIsParsing(false);
    }
  };

  const handleFileInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (files && files.length > 0) {
      handleFileProcess(files[0]);
    }
  };

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(true);
  };

  const handleDragLeave = () => {
    setIsDragging(false);
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
    if (e.dataTransfer.files && e.dataTransfer.files.length > 0) {
      handleFileProcess(e.dataTransfer.files[0]);
    }
  };

  const handleReset = () => {
    setFile(null);
    setFileName("");
    setFileSize("");
    setParsedRows([]);
    setParseError(null);
    setSubmitError(null);
    setSubmitSuccess(null);
    if (fileInputRef.current) {
      fileInputRef.current.value = "";
    }
  };

  // Submit parsed tokens to backend
  const handleSubmit = async () => {
    if (parsedRows.length === 0) return;
    setIsSubmitting(true);
    setSubmitError(null);
    setSubmitSuccess(null);

    try {
      const response = await fetch("/api/admin/employee-tokens/import-excel", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${activeToken}`,
        },
        body: JSON.stringify({
          mode: importMode,
          tokens: parsedRows.map((r) => ({
            username: r.username,
            roleName: r.roleName,
            cdaRoleName: r.cdaRoleName,
            hasCdaAccess: r.hasCdaAccess,
            discordTag: r.discordTag,
            token: r.token,
            hideFromHierarchy: r.hideFromHierarchy,
            isDev: r.isDev,
          })),
        }),
      });

      const data = await response.json();
      if (!response.ok) {
        throw new Error(data.error || "Errore durante l'applicazione dei token.");
      }

      setSubmitSuccess(data.message);
      setTimeout(() => {
        onSuccess(parsedRows.length, importMode);
        onClose();
      }, 1500);
    } catch (err: any) {
      console.error("Error submitting import:", err);
      setSubmitError(err.message || "Errore di connessione al server.");
    } finally {
      setIsSubmitting(false);
    }
  };

  const filteredPreview = parsedRows.filter(
    (row) =>
      row.username.toLowerCase().includes(searchTerm.toLowerCase()) ||
      row.roleName.toLowerCase().includes(searchTerm.toLowerCase()) ||
      (row.token || "").toLowerCase().includes(searchTerm.toLowerCase()) ||
      (row.discordTag || "").toLowerCase().includes(searchTerm.toLowerCase())
  );

  const newCount = parsedRows.filter((r) => r.isNew).length;
  const updateCount = parsedRows.filter((r) => !r.isNew).length;
  const autoTokenCount = parsedRows.filter((r) => r.isTokenAutoGenerated).length;

  return (
    <div className="fixed inset-0 z-50 bg-black/85 backdrop-blur-sm flex items-center justify-center p-3 sm:p-5 overflow-y-auto">
      <motion.div
        initial={{ opacity: 0, scale: 0.96 }}
        animate={{ opacity: 1, scale: 1 }}
        exit={{ opacity: 0, scale: 0.96 }}
        className="bg-[#131418] border border-white/10 rounded-2xl w-full max-w-4xl shadow-2xl overflow-hidden flex flex-col max-h-[92vh]"
      >
        {/* Modal Header */}
        <div className="px-6 py-4 bg-gradient-to-r from-blue-950/40 via-slate-900 to-indigo-950/40 border-b border-white/10 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-blue-600/20 border border-blue-500/40 flex items-center justify-center text-blue-400 shadow-inner">
              <FileSpreadsheet size={22} />
            </div>
            <div>
              <h3 className="text-base sm:text-lg font-bold text-white flex items-center gap-2">
                Riscrivi & Importa Token da Foglio Excel
              </h3>
              <p className="text-xs text-slate-400">
                Aggiorna o sostituisci in massa i token del personale caricando un file .xlsx, .xls o .csv
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            disabled={isSubmitting}
            className="text-slate-400 hover:text-white p-2 rounded-lg hover:bg-white/5 transition-colors cursor-pointer"
          >
            <X size={20} />
          </button>
        </div>

        {/* Modal Body */}
        <div className="p-6 space-y-5 overflow-y-auto flex-1 custom-scrollbar">
          {/* Instructions and Download Template Card */}
          <div className="p-4 bg-white/5 border border-white/10 rounded-xl flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
            <div className="flex items-start gap-2.5">
              <HelpCircle className="w-5 h-5 text-indigo-400 shrink-0 mt-0.5" />
              <div className="text-xs text-slate-300">
                <span className="font-bold text-white block mb-0.5">Formato colonne supportato:</span>
                <span>Nome e Cognome, Grado / Ruolo EMS, Ruolo CDA (opzionale), Tag Discord, Token di Accesso</span>
              </div>
            </div>
            <div className="flex items-center gap-2 shrink-0 w-full sm:w-auto">
              <button
                type="button"
                onClick={() => handleDownloadTemplate("xlsx")}
                className="flex-1 sm:flex-none px-3 py-1.5 bg-emerald-600/20 hover:bg-emerald-600/30 text-emerald-300 border border-emerald-500/30 rounded-lg text-xs font-semibold flex items-center justify-center gap-1.5 transition-all cursor-pointer"
                title="Scarica file modello Excel pronto da compilare"
              >
                <Download size={14} />
                <span>Modello .xlsx</span>
              </button>
              <button
                type="button"
                onClick={() => handleDownloadTemplate("csv")}
                className="flex-1 sm:flex-none px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 rounded-lg text-xs font-semibold flex items-center justify-center gap-1.5 transition-all cursor-pointer"
                title="Scarica file modello CSV"
              >
                <Download size={14} />
                <span>Modello .csv</span>
              </button>
            </div>
          </div>

          {/* Upload or Drop Area */}
          {!file ? (
            <div
              onDragOver={handleDragOver}
              onDragLeave={handleDragLeave}
              onDrop={handleDrop}
              onClick={() => fileInputRef.current?.click()}
              className={`p-8 border-2 border-dashed rounded-xl flex flex-col items-center justify-center text-center cursor-pointer transition-all ${
                isDragging
                  ? "border-blue-500 bg-blue-500/10 scale-[0.99]"
                  : "border-white/15 bg-white/[0.02] hover:bg-white/[0.04] hover:border-blue-500/40"
              }`}
            >
              <input
                ref={fileInputRef}
                type="file"
                accept=".xlsx,.xls,.csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel,text/csv"
                onChange={handleFileInputChange}
                className="hidden"
              />
              <div className="w-14 h-14 rounded-2xl bg-blue-500/10 border border-blue-500/30 flex items-center justify-center text-blue-400 mb-3 shadow-lg">
                <Upload size={26} />
              </div>
              <p className="text-sm font-bold text-white mb-1">
                Trascina qui il file Excel o fai clic per selezionarlo
              </p>
              <p className="text-xs text-slate-400">
                Supporta file di calcolo <span className="text-blue-400 font-mono">.XLSX</span>,{" "}
                <span className="text-blue-400 font-mono">.XLS</span> e{" "}
                <span className="text-blue-400 font-mono">.CSV</span>
              </p>
            </div>
          ) : (
            <div className="p-4 bg-blue-950/20 border border-blue-500/30 rounded-xl flex items-center justify-between gap-3">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-emerald-500/20 border border-emerald-500/40 flex items-center justify-center text-emerald-400 shrink-0">
                  <FileText size={20} />
                </div>
                <div>
                  <p className="text-sm font-bold text-white truncate max-w-sm">{fileName}</p>
                  <p className="text-xs text-slate-400">
                    Dimensione: {fileSize} • Righe rilevate:{" "}
                    <span className="text-emerald-400 font-bold">{parsedRows.length}</span>
                  </p>
                </div>
              </div>
              <button
                type="button"
                onClick={handleReset}
                disabled={isSubmitting}
                className="px-3 py-1.5 bg-rose-500/20 hover:bg-rose-500/30 text-rose-300 border border-rose-500/30 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-all cursor-pointer"
              >
                <Trash2 size={14} />
                <span>Rimuovi File</span>
              </button>
            </div>
          )}

          {/* Error Banner */}
          {parseError && (
            <div className="p-4 bg-rose-950/40 border border-rose-500/30 rounded-xl text-rose-300 text-xs flex items-start gap-2.5">
              <AlertTriangle className="w-4 h-4 text-rose-400 shrink-0 mt-0.5" />
              <div>
                <span className="font-bold block text-rose-200">Errore di lettura del file:</span>
                <span>{parseError}</span>
              </div>
            </div>
          )}

          {/* Options & Preview Section (Visible when rows parsed) */}
          {parsedRows.length > 0 && (
            <div className="space-y-4">
              {/* Import Mode Selector */}
              <div>
                <label className="block text-xs font-bold uppercase tracking-wider text-slate-300 mb-2">
                  Modalità di Riscrizione del Registro
                </label>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  {/* Mode 1: Overwrite */}
                  <label
                    className={`p-3.5 rounded-xl border flex items-start gap-3 cursor-pointer transition-all ${
                      importMode === "overwrite"
                        ? "bg-amber-950/30 border-amber-500/50 ring-1 ring-amber-500/40"
                        : "bg-white/[0.02] border-white/10 hover:border-white/20"
                    }`}
                  >
                    <input
                      type="radio"
                      name="importMode"
                      value="overwrite"
                      checked={importMode === "overwrite"}
                      onChange={() => setImportMode("overwrite")}
                      className="mt-0.5 text-amber-500 focus:ring-amber-500 accent-amber-500"
                    />
                    <div>
                      <span className="font-bold text-xs text-amber-200 flex items-center gap-1.5">
                        <AlertTriangle size={14} className="text-amber-400" />
                        Riscrivi / Sostituisci Registro Completo
                      </span>
                      <p className="text-[11px] text-slate-300 mt-1 leading-relaxed">
                        Sostituisce tutti i token dipendenti con quelli del foglio Excel. I token non presenti nel file verranno revocati.{" "}
                        <span className="text-amber-300/90 font-medium">
                          (I Proprietari Ufficiali e la Master Key rimangono sempre preservati al 100%).
                        </span>
                      </p>
                    </div>
                  </label>

                  {/* Mode 2: Merge */}
                  <label
                    className={`p-3.5 rounded-xl border flex items-start gap-3 cursor-pointer transition-all ${
                      importMode === "merge"
                        ? "bg-emerald-950/30 border-emerald-500/50 ring-1 ring-emerald-500/40"
                        : "bg-white/[0.02] border-white/10 hover:border-white/20"
                    }`}
                  >
                    <input
                      type="radio"
                      name="importMode"
                      value="merge"
                      checked={importMode === "merge"}
                      onChange={() => setImportMode("merge")}
                      className="mt-0.5 text-emerald-500 focus:ring-emerald-500 accent-emerald-500"
                    />
                    <div>
                      <span className="font-bold text-xs text-emerald-200 flex items-center gap-1.5">
                        <CheckCircle2 size={14} className="text-emerald-400" />
                        Aggiorna ed Unisci (Merge)
                      </span>
                      <p className="text-[11px] text-slate-300 mt-1 leading-relaxed">
                        Aggiorna i dipendenti e ruoli già esistenti e aggiunge i nuovi token, senza eliminare i dipendenti già registrati che non figurano nel foglio.
                      </p>
                    </div>
                  </label>
                </div>
              </div>

              {/* Stats Bar & Filter */}
              <div className="flex flex-wrap items-center justify-between gap-3 pt-2">
                <div className="flex flex-wrap items-center gap-2 text-xs">
                  <span className="px-2.5 py-1 bg-white/5 border border-white/10 rounded-lg text-slate-300 font-medium">
                    Totale: <strong className="text-white">{parsedRows.length}</strong> dipendenti
                  </span>
                  <span className="px-2.5 py-1 bg-emerald-500/10 border border-emerald-500/30 rounded-lg text-emerald-300 font-medium">
                    Nuovi: <strong>{newCount}</strong>
                  </span>
                  <span className="px-2.5 py-1 bg-blue-500/10 border border-blue-500/30 rounded-lg text-blue-300 font-medium">
                    Aggiornamenti: <strong>{updateCount}</strong>
                  </span>
                  {autoTokenCount > 0 && (
                    <span className="px-2.5 py-1 bg-purple-500/10 border border-purple-500/30 rounded-lg text-purple-300 font-medium">
                      Token Generati: <strong>{autoTokenCount}</strong>
                    </span>
                  )}
                </div>

                <div className="relative w-full sm:w-64">
                  <Search className="w-3.5 h-3.5 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
                  <input
                    type="text"
                    value={searchTerm}
                    onChange={(e) => setSearchTerm(e.target.value)}
                    placeholder="Cerca nella tabella..."
                    className="w-full pl-8 pr-3 py-1.5 bg-[#0d0e12] border border-white/10 rounded-lg text-xs text-white placeholder:text-slate-500 focus:outline-hidden focus:border-blue-500"
                  />
                </div>
              </div>

              {/* Preview Table */}
              <div className="border border-white/10 rounded-xl overflow-hidden bg-[#0e0f14] max-h-60 overflow-y-auto">
                <table className="w-full text-left text-xs border-collapse">
                  <thead className="sticky top-0 bg-[#16171d] border-b border-white/10 text-[10px] uppercase font-bold text-slate-400 tracking-wider z-10">
                    <tr>
                      <th className="py-2 px-3">#</th>
                      <th className="py-2 px-3">Dipendente</th>
                      <th className="py-2 px-3">Ruolo EMS</th>
                      <th className="py-2 px-3">Ruolo CDA</th>
                      <th className="py-2 px-3">Tag Discord</th>
                      <th className="py-2 px-3">Token</th>
                      <th className="py-2 px-3 text-right">Stato</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-white/5">
                    {filteredPreview.length === 0 ? (
                      <tr>
                        <td colSpan={7} className="py-6 text-center text-slate-500">
                          Nessun elemento corrispondente alla ricerca.
                        </td>
                      </tr>
                    ) : (
                      filteredPreview.map((row, idx) => (
                        <tr key={idx} className="hover:bg-white/[0.03] transition-colors">
                          <td className="py-2 px-3 text-slate-500 font-mono text-[11px]">
                            {idx + 1}
                          </td>
                          <td className="py-2 px-3 font-semibold text-slate-200">
                            {row.username}
                          </td>
                          <td className="py-2 px-3">
                            <span
                              className={`px-2 py-0.5 rounded text-[11px] font-medium ${
                                row.roleRecognized
                                  ? "bg-slate-800 text-slate-300 border border-white/10"
                                  : "bg-amber-500/10 text-amber-300 border border-amber-500/30"
                              }`}
                            >
                              {row.roleName}
                            </span>
                          </td>
                          <td className="py-2 px-3 text-slate-400">
                            {row.cdaRoleName ? (
                              <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-amber-500/10 text-amber-300 border border-amber-500/30">
                                {row.cdaRoleName}
                              </span>
                            ) : (
                              <span className="text-slate-600">-</span>
                            )}
                          </td>
                          <td className="py-2 px-3 text-indigo-300 font-mono text-[11px]">
                            {row.discordTag || "-"}
                          </td>
                          <td className="py-2 px-3 font-mono font-bold text-slate-200 text-[11px]">
                            {row.token}
                          </td>
                          <td className="py-2 px-3 text-right">
                            {row.isNew ? (
                              <span className="px-1.5 py-0.5 bg-emerald-500/15 text-emerald-300 border border-emerald-500/30 rounded text-[10px] font-bold">
                                Nuovo
                              </span>
                            ) : (
                              <span className="px-1.5 py-0.5 bg-blue-500/15 text-blue-300 border border-blue-500/30 rounded text-[10px] font-bold">
                                Aggiorna
                              </span>
                            )}
                          </td>
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* Submit Error Banner */}
          {submitError && (
            <div className="p-4 bg-rose-950/50 border border-rose-500/40 rounded-xl text-rose-300 text-xs flex items-center gap-2">
              <AlertTriangle className="w-4 h-4 text-rose-400 shrink-0" />
              <span>{submitError}</span>
            </div>
          )}

          {/* Submit Success Banner */}
          {submitSuccess && (
            <div className="p-4 bg-emerald-950/50 border border-emerald-500/40 rounded-xl text-emerald-300 text-xs flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
              <span>{submitSuccess}</span>
            </div>
          )}
        </div>

        {/* Modal Footer */}
        <div className="px-6 py-4 bg-[#101115] border-t border-white/10 flex flex-wrap items-center justify-between gap-3">
          <button
            type="button"
            onClick={onClose}
            disabled={isSubmitting}
            className="px-4 py-2 bg-white/5 hover:bg-white/10 text-slate-300 font-bold text-xs rounded-xl border border-white/10 transition-colors cursor-pointer"
          >
            Annulla
          </button>

          <div className="flex items-center gap-2">
            {parsedRows.length > 0 && (
              <button
                type="button"
                onClick={handleSubmit}
                disabled={isSubmitting}
                className={`px-5 py-2.5 text-white font-bold text-xs rounded-xl shadow-lg flex items-center gap-2 cursor-pointer transition-all active:scale-95 ${
                  importMode === "overwrite"
                    ? "bg-amber-600 hover:bg-amber-500 border border-amber-500/40"
                    : "bg-emerald-600 hover:bg-emerald-500 border border-emerald-500/40"
                } ${isSubmitting ? "opacity-60 cursor-not-allowed" : ""}`}
              >
                {isSubmitting ? (
                  <>
                    <RefreshCw className="w-4 h-4 animate-spin" />
                    <span>Riscrizione in corso...</span>
                  </>
                ) : importMode === "overwrite" ? (
                  <>
                    <AlertTriangle size={15} />
                    <span>Conferma Riscrizione Totale ({parsedRows.length} Token)</span>
                  </>
                ) : (
                  <>
                    <Check size={15} />
                    <span>Conferma Unione ({parsedRows.length} Token)</span>
                  </>
                )}
              </button>
            )}
          </div>
        </div>
      </motion.div>
    </div>
  );
};
